openapi: 3.0.0
info:
  title: IGDB Data Extraction API
  version: 1.0.0
  description: This API allows extraction of data from the IGDB API and stores it in Azure Blob Storage.
  contact:
    name: API Support
    url: https://github.com/lessing-anderson
    email: lessing.anderson@
servers:
  - url: http://localhost:7071
    description: Local server
  - url: https://{your-function-app-name}.azurewebsites.net/
    description: Production server
    variables:
      your-function-app-name:
        default: data-extraction-app-dev
        description: The name of your Azure Function App
paths:
  /igdb/extract:
    post:
      summary: Extract data from IGDB API
      description: This endpoint extracts data from the IGDB API based on the provided parameters and stores it in Azure Blob Storage.
      parameters:
        - name: code
          in: query
          required: true
          description: Function key for authentication
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                endpoint:
                  type: string
                  description: The endpoint to extract data from.
                  example: games
                extract_type:
                  type: string
                  description: The type of extraction to perform.
                  enum: [full, delta]
                  example: delta
                delta_days:
                  type: integer
                  description: The number of days for delta extraction.
                  example: 1
                account_name:
                  type: string
                  description: The name of the Azure Storage account.
                  example: dlhsheepdev
                storage_path:
                  type: string
                  description: The path in the storage container to save the data.
                  example: IGDB/
              required:
                - endpoint
                - extract_type
                - account_name
                - storage_path
      responses:
        '200':
          description: Successful extraction
          content:
            text/plain:
              schema:
                type: string
                example: This HTTP triggered function executed successfully.
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid request parameters.
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: An error occurred while processing the request.
components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
security:
  - apiKeyAuth: []
tags:
  - name: IGDB
    description: Operations related to IGDB data extraction